### ISSUE TITLE
user can see their car

### ISSUE THREAD

**Issue by bernardino8** [bernardino8/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x]  create the necessary files to work w/
    * index page, stylesheet (layout.css, utility.css, main.css), script, etc? 
- [x]  create the layout of the index page
    * will a container(s), row(s), column(s), etc, be necessary? will we use a display property(s), and if so, what value will it (they) have? etc
- [x]  create the necessary elements in the index page
    * include favicon, etc?
- [x]  create a stylesheet accordingly
    * green background; will we need to modify/adjust the car svg, etc?
