### ISSUE TITLE
user can turn their car

### ISSUE THREAD

**Issue by bernardino8** [bernardino8/driving-game#3]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] create a class for each respective key (i.e., left, up, right, down)
- [x] set class on the image element
- [x] add an event listener for the window on the keydown event
- [x] get event key for the respective keydown key (i.e., event key for pressing down the left key, etc)
- [x] update class in respect to the key the user is pressing
