### ISSUE TITLE
user can start their car

### ISSUE THREAD

**Issue by bernardino8** [bernardino8/driving-game#5]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [ ] give the image element new properties/values in the stylesheet 
- [ ] query the image's x/y coordinates via offset
- [ ] update image's top and left offset 
- [ ] create an interval function; move image every 16ms
